/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAMSUNG
 */
public class manual extends javax.swing.JFrame {

    /**
     * Creates new form manual
     */
    public manual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();
        btnquestion1 = new javax.swing.JButton();
        btnquestion2 = new javax.swing.JButton();
        btnquestion3 = new javax.swing.JButton();
        btnquestion4 = new javax.swing.JButton();
        btnquestion5 = new javax.swing.JButton();
        btnquestion6 = new javax.swing.JButton();
        btnquestion7 = new javax.swing.JButton();
        btnquestion8 = new javax.swing.JButton();
        btnquestion9 = new javax.swing.JButton();
        btnquestion10 = new javax.swing.JButton();
        btnquestion11 = new javax.swing.JButton();
        btnquestion12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        textarea.setEditable(false);
        textarea.setColumns(20);
        textarea.setLineWrap(true);
        textarea.setRows(5);
        textarea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textarea);

        btnquestion1.setText("How to use this system?");
        btnquestion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquestion1ActionPerformed(evt);
            }
        });

        btnquestion2.setText("How to remove tenants?");
        btnquestion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquestion2ActionPerformed(evt);
            }
        });

        btnquestion3.setText("How to add tenants?");
        btnquestion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquestion3ActionPerformed(evt);
            }
        });

        btnquestion4.setText("How to update status concerns?");
        btnquestion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquestion4ActionPerformed(evt);
            }
        });

        btnquestion5.setText("How to create staff account?");
        btnquestion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquestion5ActionPerformed(evt);
            }
        });

        btnquestion6.setText("How to remove accounts?");
        btnquestion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquestion6ActionPerformed(evt);
            }
        });

        btnquestion7.setText("How to view conerns");
        btnquestion7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquestion7ActionPerformed(evt);
            }
        });

        btnquestion8.setText("View all conerns");
        btnquestion8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquestion8ActionPerformed(evt);
            }
        });

        btnquestion9.setText("How to use this system?");
        btnquestion9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquestion9ActionPerformed(evt);
            }
        });

        btnquestion10.setText("How to remove tenants?");
        btnquestion10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquestion10ActionPerformed(evt);
            }
        });

        btnquestion11.setText("How this system work?");
        btnquestion11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquestion11ActionPerformed(evt);
            }
        });

        btnquestion12.setText("How to login account?");
        btnquestion12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquestion12ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUESTIONS?");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SYSTEM:");

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CLOSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnquestion9, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnquestion10)
                            .addGap(61, 61, 61)
                            .addComponent(btnquestion11, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(68, 68, 68)
                            .addComponent(btnquestion12, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnquestion5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnquestion6)
                            .addGap(73, 73, 73)
                            .addComponent(btnquestion7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnquestion8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnquestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnquestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btnquestion3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(btnquestion4)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnquestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnquestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnquestion3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnquestion4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnquestion5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnquestion6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnquestion7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnquestion8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnquestion9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnquestion10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnquestion11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnquestion12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnquestion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquestion1ActionPerformed
       // Append user question
    textarea.append("User: How to use this system?\n");
    
    // Append system response
    textarea.append("System: To use this system, log in with your credentials and navigate through the modules on the dashboard.\n\n");
    }//GEN-LAST:event_btnquestion1ActionPerformed

    private void btnquestion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquestion2ActionPerformed
       textarea.append("User: How to remove tenants?\n");
    textarea.append("System: Go to the Tenant Management module, select the tenant, and click the 'Remove' button to delete their record.\n\n");
    }//GEN-LAST:event_btnquestion2ActionPerformed

    private void btnquestion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquestion3ActionPerformed
       textarea.append("User: How to add tenants?\n");
    textarea.append("System: Navigate to the Tenant Management module and click 'Add'. Fill out the tenant's details and save.\n\n");
    }//GEN-LAST:event_btnquestion3ActionPerformed

    private void btnquestion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquestion4ActionPerformed
       textarea.append("User: How to update status concerns?\n");
    textarea.append("System: Go to the Concern Management section, select a concern, and update its status (e.g., Pending, Resolved).\n\n");
    }//GEN-LAST:event_btnquestion4ActionPerformed

    private void btnquestion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquestion5ActionPerformed
         textarea.append("User: How to create staff account?\n");
    textarea.append("System: In the Account Management module, click 'Add Account', enter the staff details, and set the role to 'staff'.\n\n");
    }//GEN-LAST:event_btnquestion5ActionPerformed

    private void btnquestion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquestion6ActionPerformed
         textarea.append("User: How to remove accounts?\n");
    textarea.append("System: Select the user from the Account Management list and click 'Remove' or set the account as inactive.\n\n");
    }//GEN-LAST:event_btnquestion6ActionPerformed

    private void btnquestion7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquestion7ActionPerformed
        textarea.append("User: How to view concerns?\n");
    textarea.append("System: Open the Concern Management module to see all submitted tenant concerns.\n\n");
    }//GEN-LAST:event_btnquestion7ActionPerformed

    private void btnquestion8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquestion8ActionPerformed
       textarea.append("User: View all concerns\n");
    textarea.append("System: Go to the Concern List section. You will see a table displaying all tenant concerns with their status and details.\n\n");
    }//GEN-LAST:event_btnquestion8ActionPerformed

    private void btnquestion9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquestion9ActionPerformed
       textarea.append("User: How to use this system?\n");
    textarea.append("System: Use the navigation menu to access modules like Tenant, Staff, and Concern Management. Each section has its own set of functions.\n\n");
    }//GEN-LAST:event_btnquestion9ActionPerformed

    private void btnquestion10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquestion10ActionPerformed
        textarea.append("User: How to remove tenants?\n");
    textarea.append("System: Go to Tenant Management, select the tenant from the list, and click 'Remove'.\n\n");
    }//GEN-LAST:event_btnquestion10ActionPerformed

    private void btnquestion11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquestion11ActionPerformed
        textarea.append("User: How this system work?\n");
    textarea.append("System: This system allows admins and staff to manage tenants, record concerns, and monitor account activities through different modules.\n\n");
    }//GEN-LAST:event_btnquestion11ActionPerformed

    private void btnquestion12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquestion12ActionPerformed
      textarea.append("User: How to login account?\n");
    textarea.append("System: On the login screen, enter your username and password, then click 'Login' to access the system.\n\n");
    }//GEN-LAST:event_btnquestion12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new AdminDashboard().setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnquestion1;
    private javax.swing.JButton btnquestion10;
    private javax.swing.JButton btnquestion11;
    private javax.swing.JButton btnquestion12;
    private javax.swing.JButton btnquestion2;
    private javax.swing.JButton btnquestion3;
    private javax.swing.JButton btnquestion4;
    private javax.swing.JButton btnquestion5;
    private javax.swing.JButton btnquestion6;
    private javax.swing.JButton btnquestion7;
    private javax.swing.JButton btnquestion8;
    private javax.swing.JButton btnquestion9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textarea;
    // End of variables declaration//GEN-END:variables
}
